// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Author.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Author {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var firstName: String {
    get {return _firstName ?? String()}
    set {_firstName = newValue}
  }
  /// Returns true if `firstName` has been explicitly set.
  var hasFirstName: Bool {return self._firstName != nil}
  /// Clears the value of `firstName`. Subsequent reads from it will return its default value.
  mutating func clearFirstName() {self._firstName = nil}

  var lastName: String {
    get {return _lastName ?? String()}
    set {_lastName = newValue}
  }
  /// Returns true if `lastName` has been explicitly set.
  var hasLastName: Bool {return self._lastName != nil}
  /// Clears the value of `lastName`. Subsequent reads from it will return its default value.
  mutating func clearLastName() {self._lastName = nil}

  var birthDate: Int64 {
    get {return _birthDate ?? 0}
    set {_birthDate = newValue}
  }
  /// Returns true if `birthDate` has been explicitly set.
  var hasBirthDate: Bool {return self._birthDate != nil}
  /// Clears the value of `birthDate`. Subsequent reads from it will return its default value.
  mutating func clearBirthDate() {self._birthDate = nil}

  var psuedonyms: [String] = []

  /// Can't do optional repeated properties
  var books: [Book] = []

  var awards: [Award] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _firstName: String? = nil
  fileprivate var _lastName: String? = nil
  fileprivate var _birthDate: Int64? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Author: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Author: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Author"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "firstName"),
    2: .same(proto: "lastName"),
    3: .same(proto: "birthDate"),
    4: .same(proto: "psuedonyms"),
    5: .same(proto: "books"),
    6: .same(proto: "awards"),
  ]

  public var isInitialized: Bool {
    if self._firstName == nil {return false}
    if self._lastName == nil {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.books) {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.awards) {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._firstName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._lastName) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self._birthDate) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.psuedonyms) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.books) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.awards) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._firstName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._birthDate {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    } }()
    if !self.psuedonyms.isEmpty {
      try visitor.visitRepeatedStringField(value: self.psuedonyms, fieldNumber: 4)
    }
    if !self.books.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.books, fieldNumber: 5)
    }
    if !self.awards.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.awards, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Author, rhs: Author) -> Bool {
    if lhs._firstName != rhs._firstName {return false}
    if lhs._lastName != rhs._lastName {return false}
    if lhs._birthDate != rhs._birthDate {return false}
    if lhs.psuedonyms != rhs.psuedonyms {return false}
    if lhs.books != rhs.books {return false}
    if lhs.awards != rhs.awards {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
